name: Rancher OpenResty Proxy
description: "Automatic OpenResty Proxy for Rancher with Let's Encrypt support"
version: "v0.0.1"
category: Proxy
maintainer: mmckenzie
license: MIT
projectURl: "https://github.com/vostro/rancher-openresty-proxy"